# Generated by Django 4.2.5 on 2025-04-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('with_profile_1', models.DecimalField(decimal_places=2, help_text='Profilga kirish orqali 1-oy', max_digits=10)),
                ('with_profile_12', models.DecimalField(decimal_places=2, help_text='Profilga kirish orqali 12-oy', max_digits=10)),
                ('with_gift_3', models.DecimalField(decimal_places=2, help_text='Gift orqali 3-oy', max_digits=10)),
                ('with_gift_6', models.DecimalField(decimal_places=2, help_text='Gift orqali 6-oy', max_digits=10)),
                ('with_gift_12', models.DecimalField(decimal_places=2, help_text='Gift orqali 12-oy', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'prices',
            },
        ),
    ]
