# Generated by Django 4.2.5 on 2025-04-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_prices'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarsPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_50', models.DecimalField(decimal_places=2, help_text='50 Stars narxi', max_digits=10)),
                ('price_75', models.DecimalField(decimal_places=2, help_text='75 Stars narxi', max_digits=10)),
                ('price_100', models.DecimalField(decimal_places=2, help_text='100 Stars narxi', max_digits=10)),
                ('price_150', models.DecimalField(decimal_places=2, help_text='150 Stars narxi', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Stars narx',
                'verbose_name_plural': 'Stars narxlari',
                'db_table': 'star_prices',
            },
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'Premium narx', 'verbose_name_plural': 'Premium narxlari'},
        ),
    ]
