# Generated by Django 4.2.5 on 2025-04-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_starsprices_alter_prices_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Jami summasi', max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Hozirgi summasi', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_url', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ovoz beriladigan kanal')),
                ('elementary_bonus', models.DecimalField(blank=True, decimal_places=2, help_text="Boshlang'ich bonus narxi", max_digits=10, null=True)),
                ('daily_bonus', models.DecimalField(blank=True, decimal_places=2, help_text='Kunlik bonus narxi', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
