# Generated by Django 4.2.5 on 2025-04-19 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuseraccount_rewards'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rewards',
            new_name='RewardsChannelBoost',
        ),
    ]
