# Generated by Django 4.2.5 on 2025-04-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_rewards_rewardschannelboost'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('rewards_channel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.rewardschannelboost')),
            ],
            options={
                'verbose_name': 'Kunlik bonus',
                'verbose_name_plural': 'Kunlik bonuslar',
                'db_table': 'daily_bonus',
                'indexes': [models.Index(fields=['chat_id', 'rewards_channel'], name='daily_bonus_chat_id_4ee372_idx')],
            },
        ),
    ]
