# Generated by Django 4.2.5 on 2025-04-19 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_dailybonus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryBonusAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Story bonuslar',
                'verbose_name_plural': 'Story bonuslar',
                'db_table': 'story_bonus',
            },
        ),
        migrations.CreateModel(
            name='StoryBonusPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text="Boshlang'ich bonus narxi", max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Story narx',
                'verbose_name_plural': 'Story narxlar',
                'db_table': 'story_bonus_price',
            },
        ),
        migrations.AddField(
            model_name='dailybonus',
            name='last_bonus',
            field=models.DateField(blank=True, null=True),
        ),
    ]
