# Generated by Django 4.2.5 on 2025-04-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_storybonusaccounts_storybonusprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('new_user_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Gruppaga qo'shganlar",
                'verbose_name_plural': "Gruppaga qo'shilganlar",
                'db_table': 'invited_user',
            },
        ),
    ]
