# Generated by Django 4.2.5 on 2025-04-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_inviteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='limit',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Qo'shish kerak bo'lgan limit"),
        ),
        migrations.AddField(
            model_name='group',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Qo'shganlik uchun summa: "),
        ),
    ]
