# Generated by Django 4.2.5 on 2025-04-21 16:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_group_limit_group_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedBonusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('clean', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.group')),
            ],
            options={
                'verbose_name': "Gruppaga qo'shilganlar bonuslar",
                'verbose_name_plural': "Gruppaga qo'shilganlar bonuslari",
                'db_table': 'invited_user_bonus',
            },
        ),
    ]
