# Generated by Django 4.2.5 on 2025-04-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_invitedbonususer'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestingBonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.DecimalField(decimal_places=2, help_text='Bio summasi', max_digits=10)),
                ('fullname', models.DecimalField(decimal_places=2, help_text='Nikname summasi', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qiziqarli bonus narx',
                'verbose_name_plural': 'Qiziqarli bonus narxlari',
                'db_table': 'interesting_bonus',
            },
        ),
        migrations.CreateModel(
            name='InterestingBonusUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('bio', models.BooleanField(default=False)),
                ('fullname', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qiziqarli bonus user',
                'verbose_name_plural': 'Qiziqarli bonus userlar',
                'db_table': 'interesting_user_bonus',
            },
        ),
    ]
