# Generated by Django 4.2.5 on 2025-04-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_interestingbonus_interestingbonususer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='invited_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
