# Generated by Django 4.2.5 on 2025-04-21 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customuser_invited_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
