# Generated by Django 4.2.5 on 2025-04-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_customuser_premium_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='spend_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
