# Generated by Django 4.2.5 on 2025-04-21 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_settings_spend_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sotish xabar',
                'verbose_name_plural': 'Sotish xabarlari',
                'db_table': 'spend_price',
            },
        ),
        migrations.CreateModel(
            name='SpendPriceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('spend_price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.spendprice')),
            ],
            options={
                'verbose_name': 'Sotish xabar narx',
                'verbose_name_plural': 'Sotish xabari narxlari',
                'db_table': 'spend_price_field',
            },
        ),
    ]
