# Generated by Django 4.2.5 on 2025-04-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_promocodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='chat_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
