# Generated by Django 4.2.5 on 2025-04-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_promocodes_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
