# Generated by Django 4.2.5 on 2025-04-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_customuser_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuseraccount',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Hozirgi summasi', max_digits=10),
        ),
        migrations.AlterField(
            model_name='customuseraccount',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Jami summasi', max_digits=10),
        ),
    ]
