# Generated by Django 4.2.5 on 2025-04-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_customuseraccount_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuseraccount',
            name='referral_prem_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Referral premium summasi', max_digits=10),
        ),
        migrations.AddField(
            model_name='customuseraccount',
            name='referral_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Referral summasi', max_digits=10),
        ),
    ]
