# Generated by Django 4.2.5 on 2025-04-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_remove_customuseraccount_referral_prem_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
