# Generated by Django 4.2.5 on 2025-04-28 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Majburiy azolik kanal', 'verbose_name_plural': 'Majburiy azolik kanallari'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Azolik gruppasi', 'verbose_name_plural': 'Azolik gruppasi'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Asosiy sozlama', 'verbose_name_plural': 'Asosiy sozlamalar'},
        ),
    ]
