# Generated by Django 4.2.5 on 2025-04-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_channel_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocodes',
            options={'verbose_name': 'Promo kod', 'verbose_name_plural': 'Promo kodlar'},
        ),
    ]
