# Generated by Django 4.2.5 on 2025-04-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_promocodes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodes',
            name='reward',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
