# Generated by Django 4.2.5 on 2025-04-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_promocodes_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('fullname', models.CharField(blank=True, max_length=255, null=True)),
                ('balance', models.BigIntegerField(default=0)),
                ('total_earned', models.BigIntegerField(default=0)),
                ('weekly_earned', models.BigIntegerField(default=0)),
                ('monthly_earned', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Top user',
                'verbose_name_plural': 'Top userlar',
                'db_table': 'top_user',
            },
        ),
        migrations.AddField(
            model_name='settings',
            name='promo_limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Promo limit'),
        ),
    ]
