# Generated by Django 4.2.5 on 2025-04-28 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_topuser_settings_promo_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuseraccount',
            options={'verbose_name': 'Foydalanuvchi Akkounti', 'verbose_name_plural': 'Foydalanuvchi Akkountlari'},
        ),
    ]
