# Generated by Django 4.2.5 on 2025-05-07 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_customuseraccount_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteduser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.group'),
        ),
    ]
