# Generated by Django 4.2.5 on 2025-05-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_inviteduser_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteduser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dailybonus',
            name='rewards_channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rewardschannelboost'),
        ),
    ]
