# Generated by Django 4.2.5 on 2025-05-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_inviteduser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailybonus',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
