# Generated by Django 4.2.5 on 2025-07-15 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_dailybonus_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('default', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('reward', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Custom Promo kod',
                'verbose_name_plural': 'Custom Promo kodlar',
                'db_table': 'custom_promo_codes',
            },
        ),
    ]
