# Generated by Django 4.2.5 on 2025-07-16 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_custompromocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.custompromocode')),
            ],
            options={
                'verbose_name': 'Custom Promo kod user',
                'verbose_name_plural': 'Custom Promo kod userlar',
                'db_table': 'custom_user_promo_codes',
            },
        ),
    ]
