# Generated by Django 4.2.5 on 2025-07-17 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_customuserpromocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserpromocode',
            name='chat_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
