# Generated by Django 4.2.5 on 2025-09-08 22:16

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_quiz_useranswer_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTestSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_limit', models.PositiveIntegerField(default=10, help_text='Har bir test sessiyasida nechta savol random tushadi', validators=[django.core.validators.MinValueValidator(1)])),
                ('per_correct_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Har to‘g‘ri javob uchun bonus (decimal)', max_digits=12)),
                ('full_completion_bonus', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hammasi to‘g‘ri bo‘lsa bonus (decimal)', max_digits=12)),
                ('time_limit_seconds', models.PositiveIntegerField(blank=True, help_text='Butun test uchun vaqt limiti (sekundlarda)', null=True)),
                ('max_attempts_per_user', models.PositiveIntegerField(blank=True, help_text='Foydalanuvchi uchun maksimal urinishlar soni', null=True)),
                ('daily_attempt_limit', models.PositiveIntegerField(blank=True, help_text='Kuniga maksimal urinishlar soni', null=True)),
                ('pass_threshold_correct', models.PositiveIntegerField(blank=True, help_text='O‘tish uchun zarur to‘g‘ri javoblar soni', null=True)),
                ('shuffle_options', models.BooleanField(default=True)),
                ('allow_repeat_questions', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Global Test Sozlamasi',
                'verbose_name_plural': 'Global Test Sozlamalari',
            },
        ),
    ]
