# Generated by Django 4.2.5 on 2025-09-09 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_globaltestsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='daily_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='daily_attempts_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='total_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
