# Generated by Django 4.2.5 on 2025-09-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_useranswer_daily_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltestsettings',
            name='auto_cashout_every_correct',
            field=models.PositiveIntegerField(blank=True, help_text='Nechta to‘g‘ri javobdan keyin avtomatik balansga o‘tkazilsin (masalan 10).', null=True),
        ),
        migrations.AlterField(
            model_name='globaltestsettings',
            name='allow_repeat_questions',
            field=models.BooleanField(default=False, verbose_name='Savollarni takrorlashga ruxsat berish'),
        ),
        migrations.AlterField(
            model_name='globaltestsettings',
            name='shuffle_options',
            field=models.BooleanField(default=True, verbose_name='Variantlarni aralashtirish'),
        ),
    ]
