class States:
    START = 1
    CHECK_CHANNEL = 2
    PHONE = 3
    SIGNUP = 4
    RATING = 5
    BONUS = 6
    CHANNEL_BOOST_BONUS = 7
    STORY_BONUS = 8
    GROUP = 9
    GROUP_BONUS = 10
    INTERESTING_BONUS = 11
    INTERESTING_BONUS_NIK = 12
    INTERESTING_BONUS_BIO = 13
